//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HideItBobby.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HideItBobby.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;resources&gt;
        ///  &lt;!-- language --&gt;
        ///  &lt;string name=&quot;LanguageName&quot;&gt;Deutsch&lt;/string&gt;
        ///  &lt;string name=&quot;LanguageHeader&quot;&gt;Sprache&lt;/string&gt;
        ///  &lt;string name=&quot;UseGameLanguage&quot;&gt;Spielsprache verwenden&lt;/string&gt;
        ///  &lt;string name=&quot;SelectLanguage&quot;&gt;Sprache wählen&lt;/string&gt;
        ///  &lt;!-- features --&gt;
        ///  &lt;string name=&quot;AvailableFeaturesHeader&quot;&gt;Verfügbare Funktionen&lt;/string&gt;
        ///  &lt;string name=&quot;UnavailableFeaturesHeader&quot;&gt;Nicht verfügbare Funktionen&lt;/string&gt;
        ///  &lt;string name=&quot;UnavailableFeaturesDescription&quot;&gt;In d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hide_it_bobby_de {
            get {
                return ResourceManager.GetString("hide_it_bobby_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;resources&gt;
        ///  &lt;!-- language --&gt;
        ///  &lt;string name=&quot;LanguageName&quot;&gt;English&lt;/string&gt;
        ///  &lt;string name=&quot;LanguageHeader&quot;&gt;Language&lt;/string&gt;
        ///  &lt;string name=&quot;UseGameLanguage&quot;&gt;Use game language&lt;/string&gt;
        ///  &lt;string name=&quot;SelectLanguage&quot;&gt;Select language&lt;/string&gt;
        ///  &lt;!-- features --&gt;
        ///  &lt;string name=&quot;AvailableFeaturesHeader&quot;&gt;Available features&lt;/string&gt;
        ///  &lt;string name=&quot;UnavailableFeaturesHeader&quot;&gt;Unavailable features&lt;/string&gt;
        ///  &lt;string name=&quot;UnavailableFeaturesDescription&quot;&gt;Feature [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hide_it_bobby_en {
            get {
                return ResourceManager.GetString("hide_it_bobby_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;resources&gt;
        ///  &lt;!-- language --&gt;
        ///  &lt;string name=&quot;LanguageName&quot;&gt;日本語&lt;/string&gt;
        ///  &lt;string name=&quot;LanguageHeader&quot;&gt;言語設定&lt;/string&gt;
        ///  &lt;string name=&quot;UseGameLanguage&quot;&gt;システム言語を使用&lt;/string&gt;
        ///  &lt;string name=&quot;SelectLanguage&quot;&gt;言語を選択&lt;/string&gt;
        ///  &lt;!-- features --&gt;
        ///  &lt;string name=&quot;AvailableFeaturesHeader&quot;&gt;利用可能な機能&lt;/string&gt;
        ///  &lt;string name=&quot;UnavailableFeaturesHeader&quot;&gt;利用不可の機能&lt;/string&gt;
        ///  &lt;string name=&quot;UnavailableFeaturesDescription&quot;&gt;このセクションで表示される機能は、他のMODと競合して無効になっています&lt;/string&gt;
        ///  &lt;!-- main menu --&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hide_it_bobby_ja {
            get {
                return ResourceManager.GetString("hide_it_bobby_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;resources&gt;
        ///  &lt;!-- language --&gt;
        ///  &lt;string name=&quot;LanguageName&quot;&gt;Polski&lt;/string&gt;
        ///  &lt;string name=&quot;LanguageHeader&quot;&gt;Język&lt;/string&gt;
        ///  &lt;string name=&quot;UseGameLanguage&quot;&gt;Użyj języka gry&lt;/string&gt;
        ///  &lt;string name=&quot;SelectLanguage&quot;&gt;Wybierz język&lt;/string&gt;
        ///  &lt;!-- features --&gt;
        ///  &lt;string name=&quot;AvailableFeaturesHeader&quot;&gt;Dostępne funkcje&lt;/string&gt;
        ///  &lt;string name=&quot;UnavailableFeaturesHeader&quot;&gt;Niedostępne funkcje&lt;/string&gt;
        ///  &lt;string name=&quot;UnavailableFeaturesDescription&quot;&gt;Funkcje wyświetlon [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hide_it_bobby_pl {
            get {
                return ResourceManager.GetString("hide_it_bobby_pl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;resources&gt;
        ///  &lt;!-- language --&gt;
        ///  &lt;string name=&quot;LanguageName&quot;&gt;简体中文&lt;/string&gt;
        ///  &lt;string name=&quot;LanguageHeader&quot;&gt;语言&lt;/string&gt;
        ///  &lt;string name=&quot;UseGameLanguage&quot;&gt;使用游戏默认语言&lt;/string&gt;
        ///  &lt;string name=&quot;SelectLanguage&quot;&gt;选择语言&lt;/string&gt;
        ///  &lt;!-- features --&gt;
        ///  &lt;string name=&quot;AvailableFeaturesHeader&quot;&gt;可用特性&lt;/string&gt;
        ///  &lt;string name=&quot;UnavailableFeaturesHeader&quot;&gt;不可用特性&lt;/string&gt;
        ///  &lt;string name=&quot;UnavailableFeaturesDescription&quot;&gt;由于与另一个mod冲突，在这部分可见的功能被禁用。&lt;/string&gt;
        ///  &lt;!-- main menu --&gt;
        ///  &lt;stri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hide_it_bobby_zh {
            get {
                return ResourceManager.GetString("hide_it_bobby_zh", resourceCulture);
            }
        }
    }
}
